<!DOCTYPE><html>
<head>
    <script type="text/javascript" src="//code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
    <script src="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>

    <link rel="stylesheet" type="text/css" media="screen" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css" rel="stylesheet">
    <link rel="stylesheet" href="http://v4-alpha.getbootstrap.com/assets/css/docs.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.css">
    <link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/custom.css">
</head>
<body>
<div class="container">
    <?php include('menu.phtml');?>

    <?php

    if(count($_SESSION['message']['success'])>0) {
        foreach ($_SESSION['message']['success'] as $mess) {
            ?>
            <div class="alert alert-success"><strong>Félicitations !</strong>
                <?php echo $mess; ?>
            </div>
            <?php
        }
    }
    if(count($_SESSION['message']['fail'])>0) {
        foreach($_SESSION['message']['fail'] as $mess){
            ?>
            <div class="alert alert-danger"><strong>Erreur !</strong>
                <?php echo $mess;?>
            </div>
             <?php
        }
    }
    unset($_SESSION['message']);

    ?>

    <?php echo $this->content(); ?>
    <?php include('footer.phtml');?>
</div>
</body>
</html>