<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Vente de DVD</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo WEB_ROOT; ?>/">Accueil</a></li>
                <li class="active"><a href="<?php echo WEB_ROOT; ?>/films">Films</a></li>
                <li><a href="<?php echo WEB_ROOT; ?>/categories">Catégories</a>
                <?php if($_SESSION['user']['profil']->role==2){ ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo WEB_ROOT; ?>/add/categorie">Ajouter une catégorie</a></li>
                        <li><a href="<?php echo WEB_ROOT; ?>/add/film">Ajouter un film</a></li>
                        <!--<li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>-->
                    </ul>
                </li>
                <?php } if($_SESSION['user']){
                    ?><li><a class="pull-left menu-panier" href="<?php echo WEB_ROOT; ?>/panier">Panier</a> <?php
                    if(count($_SESSION['user']['panier'])>0){
                        $total = 0;
                        foreach($_SESSION['user']['panier'] as $panier){
                            $total+=$panier['quantite'];
                        }
                        echo '<span class="pull-left fa fa-certificate"></span>
                    <span class="nbPanier">'.$total.'</span>';
                    }
                } ?></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if(!$_SESSION['user']){ ?>
                <li><a href="<?php echo WEB_ROOT; ?>/inscription">Inscription</a></li>
                <li><a href="<?php echo WEB_ROOT; ?>/login">Connexion</a></li>
                <?php } else{
                    ?>
                <li><a href="<?php echo WEB_ROOT; ?>/deconnexion">Déconnexion</a></li>
                <?php
} ?>
            </ul>
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>